name: Feature Request
description: Suggest a new capability or UX improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What are you trying to achieve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe expected behavior and UX
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Why this matters for users/project
